<!doctype html>
<html>
	<head>
		<title> PHP Error </title>

		<style type="text/css">

			body {
				margin: 50px;
				font-family: Helvetica, Verdana, Sans-serif;
				font-size: 13px;
				color: #000;
			}

			h1 {
				color: #cc0000;
				border-bottom: 1px solid #D0D0D0;
				font-size: 16px;
				font-weight: bold;
				margin: 24px 0 2px 0;
				padding: 5px 0 6px 0;
			}

			h2 {
				font-size: 18px;
			}

			.error {
				margin-top: 20px;
				padding: 20px;
				background-color: #f9eeee;
				border: 1px solid #ffcfcf;
			}

			ol {
				overflow:auto;
				font-family: Consolas, "Courier New",Courier,mono;
				margin:0;
				background-color: black;
				color: #ccc;
				width:90%;
			}
			ol li {
				background:#fff;
				font-size:small;
			}
			ol li code {color:#036; font-family: Consolas; white-space: pre;}
			ol li.active { background-color: #ffcfcf}

		</style>
	</head>
	<body>

		<h1>Oh no, something went terribly wrong!</h1>

		<div class="error">
			<h2><?= $errstr ?></h2>
			<p>An error ocurred on <strong>line <?= $errline ?></strong> in file <strong><?= $errfile ?></strong>.</p>
			<ol start="<?=$errline-3?>">
				<?php foreach ($errcode as $line => $code): ?>
					<li<?= ($line == $errline) ? ' class="active"' : '' ?>><code><?= $code ?></code></li>
				<?php endforeach; ?>
			</ol>

		</div>

	</body>
</html>