<!doctype html>
<html>
	<head>
		<title> Glenn: Demo </title>
		
		<style type="text/css">

			body {
				margin: 50px;
				font-family: Helvetica, Verdana, Sans-serif;
				font-size: 13px;
				color: #000;
			}

			h1 {
				color: #333;
				border-bottom: 1px solid #D0D0D0;
				font-size: 16px;
				font-weight: bold;
				margin: 24px 0 2px 0;
				padding: 5px 0 6px 0;
			}

			h2 {
				font-size: 18px;
			}

			.error {
				margin-top: 20px;
				padding: 20px;
				background-color: #f9eeee;
				border: 1px solid #ffcfcf;
			}

		</style>
		
	</head>
	<body>

		<h1>Hello <?= $name ?>!</h1>

	</body>
</html>